// Regenerates src/tables/*.ts from iconv-lite's mapping data (devDependency).
// Run with: npm run generate:tables
import { mkdirSync, writeFileSync } from 'node:fs';
import iconv from 'iconv-lite';

const OUT = new URL('../src/tables/', import.meta.url);
mkdirSync(OUT, { recursive: true });

const HEADER = `// Generated by scripts/generate-tables.mjs — do not edit by hand.
// Mapping data derived from iconv-lite <https://github.com/ashtuchkin/iconv-lite>,
// MIT License, Copyright (c) 2011 Alexander Shtuchkin.
`;

// Escape anything that is not unambiguously safe as a literal character in
// a TS source string: ASCII/controls, surrogates, noncharacters, BOM, and
// the JS line separators.
function isLiteralSafe(cp) {
  if (cp < 0xa1) return false;
  if (cp >= 0xd800 && cp <= 0xdfff) return false;
  if (cp >= 0xfdd0 && cp <= 0xfdef) return false;
  if (cp === 0xfeff || cp === 0xfffe || cp === 0xffff) return false;
  if (cp === 0x2028 || cp === 0x2029) return false;
  return true;
}

function lit(s) {
  let out = '"';
  for (const ch of s) {
    const cp = ch.codePointAt(0);
    out += isLiteralSafe(cp) ? ch : '\\u' + cp.toString(16).padStart(4, '0');
  }
  return out + '"';
}

// --- Single-byte code pages: 128 chars mapping bytes 0x80-0xFF ---
const SBCS = [
  'cp437', 'cp850', 'cp852', 'cp858', 'cp860', 'cp863', 'cp865', 'cp866',
  'cp1250', 'cp1251', 'cp1252', 'cp1253', 'cp1254', 'cp1255', 'cp1256',
  'cp1257', 'cp1258', 'iso88592', 'iso885915',
];

let sbcs = `${HEADER}
/** Bytes 0x80-0xFF of each code page as Unicode chars (\\uFFFD = unmapped). */
export const SBCS_TABLES: Record<string, string> = {
`;
for (const name of SBCS) {
  let table = '';
  for (let byte = 0x80; byte <= 0xff; byte++) {
    const ch = iconv.decode(Buffer.from([byte]), name);
    table += ch.length === 1 ? ch : '�';
  }
  sbcs += `  ${name}: ${lit(table)},\n`;
}
sbcs += '};\n';
writeFileSync(new URL('sbcs.ts', OUT), sbcs);

// --- Multi-byte encodings: pair string of [unicode char, code char] where
// the code char holds 1 byte (< 0x100) or 2 big-endian bytes. ---
function generatePairs(name) {
  let pairs = '';
  for (let cp = 0x80; cp <= 0xffff; cp++) {
    if (cp >= 0xd800 && cp <= 0xdfff) continue;
    const buf = iconv.encode(String.fromCharCode(cp), name);
    if (buf.length === 1) {
      if (buf[0] === 0x3f) continue; // '?' replacement → unmapped
      pairs += String.fromCharCode(cp) + String.fromCharCode(buf[0]);
    } else if (buf.length === 2) {
      pairs += String.fromCharCode(cp) + String.fromCharCode((buf[0] << 8) | buf[1]);
    }
  }
  return pairs;
}

const MBCS = ['cp932', 'gbk', 'big5', 'euckr'];
for (const name of MBCS) {
  const pairs = generatePairs(name);
  writeFileSync(
    new URL(`${name}.ts`, OUT),
    `${HEADER}// ${pairs.length / 2} mappings for ${name}.\nexport default ${lit(pairs)};\n`,
  );
  console.log(`${name}: ${pairs.length / 2} mappings`);
}
console.log('done');
